### ISSUE TITLE
Can not import opml file

### ISSUE THREAD

**Issue by Jesse-Millwood** [flathub/com.github.rssguard#23]
When I try to import an opml file the "Import from file" is never un-greyed. It does not seem to parse the file. I tried the official AppImage and it opened and parsed the opml file just fine and imported everything. I also used Flatseal to give the flatpak access to my home directory in case that was an issue and it was the same thing. This seems to only happen in the flatpak.

**Comment by Jesse-Millwood** [comment]
This is also true for the restore backup settings file dialog.

**Comment by martinrotter** [comment]
Pls, re-create the ticket in martinrotter/rssguard repo.

https://github.com/martinrotter/rssguard
